# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				creeper = true
				skeleton = true
				experience_orb = true
				zombie = true
				drowned = true
				item = true
				axolotl = true
				spider = true
				cod = true
				bat = true
				enderman = true
				dolphin = true
				chicken = true
				squid = true
				wolf = true
				bee = true
				glow_squid = true
				slime = true
				area_effect_cloud = true
				sheep = true
				pig = true
				cow = true
				tropical_fish = true
				witch = true
				cave_spider = true
				villager = true
				armor_stand = true
				painting = true
				zombie_villager = true
				iron_golem = true
				item_frame = true
				salmon = true
				arrow = true
				chest_minecart = true
				boat = true
				fox = true
				lightning_bolt = true
				skeleton_horse = true
				trident = true
				horse = true
				potion = true
				donkey = true
				pufferfish = true
				turtle = true
				pillager = true
				mooshroom = true
				guardian = true
				elder_guardian = true
				polar_bear = true
				rabbit = true
				goat = true
				parrot = true
				ocelot = true
				frog = true
				chest_boat = true
				cat = true
				snowball = true
				phantom = true
				panda = true
				fishing_bobber = true
				wandering_trader = true
				trader_llama = true
				llama_spit = true
				leash_knot = true
				wither_skeleton = true
				silverfish = true
				snow_golem = true
				egg = true
				vindicator = true
				ravager = true
				evoker = true
				vex = true
				evoker_fangs = true

			[light_sources.settings.entities.prionmod]
				vile = true
				starved = true
				lacerator = true
				fhuman = true
				deathworm = true
				necro = true
				infectedcow = true
				infectedpig = true
				envoy = true
				tumor = true
				cannibal = true
				crawler = true
				nightwalker = true
				infectedsheep = true
				bloodseeker = true
				vicoiousturret = true
				smoker = true
				nephthys = true
				noxious_sack_projectile = true
				hive = true
				lure = true
				boomer = true
				slasher = true
				wendigo = true
				slammer = true
				rooted = true
				impaler = true
				hellhound = true

			[light_sources.settings.entities.anim_guns]
				bullet = true

			[light_sources.settings.entities.bodiesbodies]
				dead_body = true

			[light_sources.settings.entities.hybrid-aquatic]
				barrel_jellyfish = true
				nomura_jellyfish = true
				starfish = true
				anglerfish = true
				sea_cucumber = true
				barreleye = true
				ratfish = true
				sea_urchin = true
				basking_shark = true
				dragonfish = true
				flashlight_fish = true
				tuna = true
				nautilus = true
				atolla_jellyfish = true
				umbrella_octopus = true
				oarfish = true
				dungeness_crab = true
				ghost_crab = true
				lightfoot_crab = true
				lions_mane_jellyfish = true
				sea_angel = true
				rockfish = true
				flower_crab = true
				coconut_crab = true
				hermit_crab = true
				crayfish = true
				cauliflower_jellyfish = true
				surgeonfish = true
				mauve_stinger = true
				moon_jellyfish = true
				triggerfish = true
				firefly_squid = true
				tiger_shark = true
				hammerhead_shark = true
				stingray = true
				fried_egg_jellyfish = true
				toadfish = true
				needlefish = true
				vampire_squid = true
				blue_jellyfish = true
				sea_nettle = true
				glowing_sucker_octopus = true
				horseshoe_crab = true
				yeti_crab = true
				spider_crab = true
				giant_isopod = true
				vampire_crab = true
				fiddler_crab = true
				manta_ray = true
				bull_shark = true
				thresher_shark = true
				great_white_shark = true
				mahi = true
				frilled_shark = true
				compass_jellyfish = true
				opah = true
				piranha = true
				tetra = true
				tiger_barb = true
				danio = true
				discus = true
				betta = true
				oscar = true
				gourami = true

			[light_sources.settings.entities.medievalweapons]
				stone_javelin = true
				iron_javelin = true
				diamond_javelin = true

			[light_sources.settings.entities.smallships]
				drakkar = true
				cog = true
				brigg = true

			[light_sources.settings.entities.doggomodoverhauled]
				doggo = true

			[light_sources.settings.entities.cave_dweller]
				cave_dweller = true

			[light_sources.settings.entities.beansbackpacks]
				backpack = true

			[light_sources.settings.entities.the_fog_is_coming]
				the_man = true
				the_man_hallucination = true
				the_man_spit = true

			[light_sources.settings.entities.niftycarts]
				supply_cart = true
				animal_cart = true
				postilion = true

