# 
# Enter the discord bot token here.
# If you don't know what this means, see the wiki:
# https://github.com/mopsy14/Minecraft-Discord-Statusbot/wiki/Getting-started
'bot_token': 'enter token here'
# 
# Change the status mode the bot will use for displaying its status message.
# Possible options are:
# playing, competing, listening, watching, (streaming is WIP and won't work)
'status_mode': 'playing'
# 
# Enter the character(s) displayed between every player name in the status message.
# Changing this to '---' would for example result in:
# playername1---playername2---playername3---playername4
'player_separator_text': ', '
# 
# Enter the status message here (using the placeholders).
# The placeholders are:
# $AOP$ being the number of players currently online on the server
# $PL$ being a list of player names separated by 'player_separator_text'
'status_message': '$AOP$ player(s) online: $PL$'
# 
# Enter the status message the bot will display when there are 0 players online.
'no_player_message': 'No one is online'
# 
# Options are true/false
# This will enable or disable the ability to use the status message sending/configuring in direct messages.
# It is recommended to disable this on larger server since the bot (and the server) may become very slow
# when using this with lots of players and registered channels.
'enable_direct_message_status_messages': 'true'
# 
# Options are true/false
# This will enable or disable the ability to use the status message sending/configuring in server channels.
# Users need at least the manage channel permission in the channel they're trying to register for the bot.
'enable_text_channel_status_messages': 'true'
# 
# Options are true/false
# This will enable or disable the sending of the server start message in both server and private channels.
'enable_server_start_messages': 'true'
# 
# This is the message that will be sent in private and server channels when the server starts.
'start_message': 'The server has started'
# 
# Options are true/false
# This will enable or disable the sending of the server stop message in both server and private channels.
'enable_server_stop_messages': 'true'
# 
# This is the message that will be sent in private and server channels when the server stops.
'stop_message': 'The server has stopped'
# 
# Options are true/false
# This will enable or disable the sending of the player join message in both server and private channels.
'enable_server_join_messages': 'true'
# 
# This is the message that will be sent in private and server channels when a player joins the Minecraft server.
# Possible placeholders are:
# $CPL$ the name of the player that joined
# $AOP$ being the number of players currently online on the server
# $PL$ being a list of player names separated by 'player_separator_text'
'join_message': 'Player $CPL$ joined the server'
# 
# Options are true/false
# This will enable or disable the sending of the player leave message in both server and private channels.
'enable_server_leave_messages': 'true'
# 
# This is the message that will be sent in private and server channels when a player leaves the Minecraft server.
# Possible placeholders are:
# $CPL$ the name of the player that left
# $AOP$ being the number of players currently online on the server
# $PL$ being a list of player names separated by 'player_separator_text'
'leave_message': 'Player $CPL$ left the server'
